# Generated by Django 5.2.17 on 2026-09-11 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE Department'), ('ECE', 'ECE Department'), ('MBA', 'MBA Department'), ('AIML', 'AIML Department')], default='CSE', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='feedback_rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '★'), (2, '★★'), (3, '★★★'), (4, '★★★★'), (5, '★★★★★')], null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='feedback_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE Department'), ('ECE', 'ECE Department'), ('MBA', 'MBA Department'), ('AIML', 'AIML Department')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20),
        ),
    ]
