# Generated by Django 5.2.17 on 2026-09-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_department_complaint_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_id', models.CharField(max_length=30, unique=True)),
                ('department', models.CharField(choices=[('CSE', 'CSE Department'), ('ECE', 'ECE Department'), ('MBA', 'MBA Department'), ('AIML', 'AIML Department'), ('AIDS', 'AIDS Department')], max_length=100)),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE Department'), ('ECE', 'ECE Department'), ('MBA', 'MBA Department'), ('AIML', 'AIML Department'), ('AIDS', 'AIDS Department')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'CSE Department'), ('ECE', 'ECE Department'), ('MBA', 'MBA Department'), ('AIML', 'AIML Department'), ('AIDS', 'AIDS Department')], max_length=100),
        ),
    ]
